"""initial schema

Revision ID: c9a72984b99e
Revises: 
Create Date: 2026-07-03 14:50:34.411375
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.database.models.json_type as appjson

revision: str = 'c9a72984b99e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postcode', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('social_links', appjson.JSONEncodedDict(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_business_dedupe_key')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_dedupe_key'), ['dedupe_key'], unique=False)

    op.create_table('suppression_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_value', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppression_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppression_list_match_value'), ['match_value'], unique=False)

    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('website_state', sa.String(length=32), nullable=False),
    sa.Column('final_url', sa.String(length=1024), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('module_results', appjson.JSONEncodedDict(), nullable=False),
    sa.Column('crawl_summary', appjson.JSONEncodedDict(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_business_id'), ['business_id'], unique=False)

    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('likelihood_of_purchase', sa.Float(), nullable=False),
    sa.Column('estimated_budget', sa.String(length=64), nullable=True),
    sa.Column('estimated_project_value', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', appjson.JSONEncodedDict(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_scores_business_id'), ['business_id'], unique=False)

    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('viewport', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshots_audit_id'), ['audit_id'], unique=False)

    op.create_table('outreach_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_score_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=False),
    sa.Column('linkedin_message', sa.Text(), nullable=False),
    sa.Column('lawful_basis_note', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('payload', appjson.JSONEncodedDict(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_score_id'], ['lead_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_drafts_lead_score_id'), ['lead_score_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_drafts_lead_score_id'))

    op.drop_table('outreach_drafts')
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshots_audit_id'))

    op.drop_table('screenshots')
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_scores_business_id'))

    op.drop_table('lead_scores')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_business_id'))

    op.drop_table('audits')
    with op.batch_alter_table('suppression_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppression_list_match_value'))

    op.drop_table('suppression_list')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_dedupe_key'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
